WT data conversion
wright-group/WrightSim pull request #45
Opened 2023-02-10 17:13 UTC by kameyer226

Closes #44 .  Comparison between original summing of values target.py and new summing shows differences, there may be an error in how summing is occurring.   Branch name is misleading.

2023-02-10 22:16 UTC, ddkohler commented
@kameyer226 I think you did not mean to delete those files?

2023-02-10 22:22 UTC, ddkohler requested changes

2023-02-10 22:22 UTC, ddkohler commented on WrightSim/wtdata.py
> +        return 0
I don't think we want this handling.  We don't want to get "0", we want an error to be raised if the function doesn't receive the right inputs.  

WIthout this try-except clause, an attribute error will be thrown the moment we try to access scan.sig.  I think that is an appropriate way to handle such a situation.

2023-02-10 22:22 UTC, ddkohler commented on WrightSim/wtdata.py
> +def convert(scan, polarizations=True, mulist=None):
Note that this implementation goes against the suggestion in issue #44 that we make wt-data objects natively.

Why don't we make scan.sig a wright tools object automatically?  i.e. Scan.run makes a WrightTools object?

2023-02-10 22:22 UTC, ddkohler commented on WrightSim/wtdata.py
> +def convert(scan, polarizations=True, mulist=None):
I think the process of making "polarization channels" should not be related to the conversion of a wt object.  e.g. what if you don't make polarization objects at creation, but at a later point you wish to create them?

I vote that the polarization channel creation should be put it in a kit module or somewhere else (or removed?)

2023-02-10 22:22 UTC, ddkohler commented on WrightSim/wtdata.py
> +                val=np.real(sig_swapped[...,idx]*mulist[idx]+np.conjugate(sig_swapped[...,idx]*mulist[idx]))
```suggestion
                val=sig_swapped[...idx].real * mulist[idx]
```

2023-02-10 22:22 UTC, ddkohler commented on WrightSim/wtdata.py
> +                data.create_channel(name='P '+scan.ham.labels[rec_idx], values=val, dtype=np.float64)
try to avoid spaces in channel names

2023-02-10 22:22 UTC, ddkohler commented on WrightSim/__init__.py
> -from . import response
why are all these removed from the module?

2023-02-10 22:22 UTC, ddkohler commented on scripts/target.py
>  # cpuSig = scan2.sig.copy()
this looks more like a test script than a target script.  I would suggest making a new script instead of rewriting the existing one.  "target" is meant to show the idealized workflow for running a simulation.

2023-02-10 22:22 UTC, ddkohler commented on WrightSim/wtdata.py
> +        return data
would be nice to transform the data before returning it.

2023-02-10 23:23 UTC, kameyer226 commented on WrightSim/__init__.py
> -from . import response
These appear to be near empty scripts relating to the application of monochromators or SLD which was thought to be left to the users to do.

2023-02-10 23:26 UTC, kameyer226 commented on WrightSim/wtdata.py
> +                val=np.real(sig_swapped[...,idx]*mulist[idx]+np.conjugate(sig_swapped[...,idx]*mulist[idx]))
ok

2023-02-10 23:31 UTC, kameyer226 commented on WrightSim/wtdata.py
> +        return 0
got it

2023-02-10 23:31 UTC, kameyer226 commented on WrightSim/wtdata.py
> +                data.create_channel(name='P '+scan.ham.labels[rec_idx], values=val, dtype=np.float64)
yes

2023-02-10 23:31 UTC, kameyer226 commented on WrightSim/wtdata.py
> +def convert(scan, polarizations=True, mulist=None):
We can definitely instantiate/populate a wt data object within the scan.run method.

Thought about polarization creating made afterwards.  We can not do at all.   But the experiment.hamiltonian.mu is the last factor of experiment.hamiltonian left in for simulation parameters.   It would be nice to separate the run result from the input parameters.

2023-02-11 16:35 UTC, ddkohler commented on WrightSim/wtdata.py
> +def convert(scan, polarizations=True, mulist=None):
I get that division between measurement and simulation is appealing, but in practice I see polarization channels as more harm than good:

1) you ~double the output size for a trivial math operation (multiplying by a constant).  In my experience it's much more efficient to just multiply the coherences by the relevant constants on the fly, rather than store the entire multiplied array.   We store the coherences from numerical integration in memory because they are computationally expensive--this multiplier operation is not expensive at all.
2) Calculating dipole-weighted arrays at wt_data creation makes it makes it more difficult to play with the weightings of each channel when you want to e.g. examine the interference of coherences.  In practice, it's useful to work with un-scaled coherences as the reference point.
3) mulists from the hamiltonian object often will not have the dipole of the emitted coherence (it is often not needed to simulate third order coherence), so it will often need to be user supplied.  

Storing these arrays are probably useful for some niche applications, but I think those applications are not general enough to be part of the wt data creation step.

2023-02-11 16:37 UTC, ddkohler commented
> Comparison between original summing of values target.py and new summing shows differences, there may be an error in how summing is occurring.

This sounds problematic.  Have you figured out the nature of the differences?  We probably don't want to merge this until we at least understand the differences...

2023-02-13 20:23 UTC, kameyer226 commented
Will close this PR and introduce a separate PR with changes more in keeping with reviewer's thoughts on incorporating wt data conversion within the scan module

2023-02-13 20:23 UTC, closed without merging